### ISSUE TITLE
CSS property for link color

### ISSUE THREAD

**Issue by Dansoftowner** [JPro-one/markdown-javafx-renderer#4]
It would be great to have a CSS property like `-mdfx-link-color` that allows to set the link color.

Then: 
```css
* {
    -mdfx-font-color: white;
    -mdfx-border-color-1: #888;

    -mdfx-bg-color-1: #484848;
    -mdfx-bg-color-2: #3c3c3c;
    -mdfx-bg-color-3: #303030;

    -mdfx-link-color: cyan;
}
```

> Note: I tried to use the class selector `.markdown-link` but somehow that didn't work for me.
